# Generated by Django 3.2.12 on 2024-12-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.TextField()),
                ('pname', models.TextField()),
                ('pdis', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('img', models.FileField(upload_to='')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.category')),
            ],
        ),
    ]
