# Generated by Django 3.2.12 on 2024-12-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0004_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField()),
                ('storage', models.TextField()),
                ('ram', models.TextField()),
                ('img', models.FileField(upload_to='')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.product')),
            ],
        ),
    ]
