# Generated by Django 3.2.12 on 2024-12-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0005_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
