# Generated by Django 5.1.6 on 2025-03-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
